import _mapKeys from 'lodash/mapKeys'
import { convert } from 'immutadot'

/**
 * Replaces by an object with the same values as the former object and values generated by running each own enumerable string keyed property of the former object thru <code>iteratee</code>.
 * The iteratee is invoked with three arguments: (value, key, object).
 * @function
 * @memberof object
 * @param {Object} object The object to modify.
 * @param {Array|string} path The path of the property to set.
 * @param {function} [iteratee={@link https://lodash.com/docs#identity|lodash.identity}] The function invoked per iteration.
 * @return {Object} Returns the updated object.
 * @example mapKeys({ nested: { a: 1, b: 2, c: 3 } }, 'nested', (v, k) => '_' + k) // => { nested: { _a: 1, _b: 2, _c: 3 } }
 * @see {@link https://lodash.com/docs#mapKeys|lodash.mapKeys} for more information.
 * @since 1.0.0
 */
const mapKeys = convert(_mapKeys)
export { mapKeys }
